version: '3'

networks:
  code-network:
    driver: bridge

services:
  nginx:
    build: ./nginx
    container_name: shop_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:cached
    links:
      - workspace
      - php
    networks:
      - code-network

  php:
    build: ./php
    container_name: shop_php
    expose:
      - 9000
    links:
      - mysql
      - redis
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:cached
    tty: true
    stdin_open: true
    environment:
      XDEBUG_CONFIG: "remote_connect_back=1; remote_enable=1;"
      PHP_IDE_CONFIG: "serverName=docker-server-mtd"
    networks:
      - code-network

  mysql:
    build: ./mysql
    container_name: shop_mysql
    user: '${APP_USER}:1000'
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
      MYSQL_ROOT_PASSWORD: root
    networks:
      - code-network

  redis:
    build: ./redis
    container_name: shop_redis
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    networks:
      - code-network

  laravel-horizon:
    build:
      context: ./laravel-horizon
      args:
        - CHANGE_SOURCE=false
        - LARADOCK_PHP_VERSION=7.4
        - INSTALL_BZ2=false
        - INSTALL_GD=false
        - INSTALL_GMP=false
        - INSTALL_GNUPG=false
        - INSTALL_LDAP=false
        - INSTALL_IMAGEMAGICK=true
        - INSTALL_PGSQL=false
        - INSTALL_ZIP_ARCHIVE=false
        - INSTALL_BCMATH=true
        - INSTALL_MEMCACHED=false
        - INSTALL_SOCKETS=false
        - INSTALL_YAML=false
        - INSTALL_CASSANDRA=false
        - INSTALL_PHPREDIS=true
        - INSTALL_MONGO=false
        - INSTALL_FFMPEG=true
        - INSTALL_AUDIOWAVEFORM=false
        - PUID=1000
        - PGID=1000
        - IMAGEMAGICK_VERSION=false
    container_name: shop_laravel_horizon
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./laravel-horizon/supervisord.d:/etc/supervisord.d
    depends_on:
      - workspace
    networks:
      - code-network

  workspace:
    build: ./workspace
    container_name: shop_workspace
    user: '${APP_USER}:1000'
    tty: true
    links:
      - mysql
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:cached
    networks:
      - code-network
