version: '3'

networks:
  code-network:
    driver: bridge

services:
  nginx:
    build: ./nginx
    container_name: shop_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:cached
    links:
      - workspace
      - php
    networks:
      - code-network

  php:
    build: ./php
    container_name: shop_php
    expose:
      - 9000
    links:
      - mysql
      - redis
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:cached
    tty: true
    stdin_open: true
    environment:
      XDEBUG_CONFIG: "remote_connect_back=1; remote_enable=1;"
      PHP_IDE_CONFIG: "serverName=docker-server-mtd"
    networks:
      - code-network

  mysql:
    build: ./mysql
    container_name: shop_mysql
    user: '${APP_USER}:1000'
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
      MYSQL_ROOT_PASSWORD: root
    networks:
      - code-network

  redis:
    build: ./redis
    container_name: shop_redis
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    networks:
      - code-network

  workspace:
    build: ./workspace
    container_name: shop_workspace
    user: '${APP_USER}:1000'
    tty: true
    links:
      - mysql
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}:cached
    networks:
      - code-network
